name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  # https://cli.github.com/manual/gh_pr
  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_repo=${{ github.repository }}
          current_pr_num=${{ github.event.number }}

          # 직전 PR 중에서 현재 PR 작성자와 다른 작성자 찾기
          previous_pr_author=$(gh pr list --repo $current_repo \
            --state all \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc -author:${{ github.actor }}" \
            --limit 3 \
            --json number,author \
            --jq "map(select(.number < $current_pr_num))[0].author.login")

          previous_pr_author2=$(gh pr list --repo $current_repo \
            --state all \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc author:${{ github.actor }}" \
            --limit 3 \
            --json number,author \
            --jq "map(select(.number < $current_pr_num))[0].author.login")

          echo "previous_pr_author: $previous_pr_author1"
          echo "previous_pr_author2: $previous_pr_author2"
          if [ -n "$previous_pr_author" ]; then
            gh pr edit $current_pr_num --repo $current_repo --add-reviewer $previous_pr_author
          else
            echo "❌ No previous PR author found to assign as reviewer"
            exit 1
          fi
