name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_repo=${{ github.repository }}
          current_pr_num=${{ github.event.number }}

          # 최근 3개의 PR 중 현재 PR 작성자와 다른 작성자 찾기
          previous_pr_author=$(gh pr list --repo $current_repo \
            --search "number:<$current_pr_num -is:closed sort:created-desc -author:$current_pr_author" \
            --limit 3 --json number,author \
            --jq '.[0].author.login')

          if [ -n "$previous_pr_author" ]; then
            gh pr edit $current_pr_num --repo $current_repo --add-reviewer bbFactory
          else
            echo "❌ No previous PR author found to assign as reviewer"
          fi
