name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_repo=${{ github.repository }}
          current_pr_num=${{ github.event.number }}

          # 직전 PR 중에서 현재 PR 작성자와 다른 작성자 찾기
          a1=$(gh pr list --repo ${{ github.repository }} \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc" \
            --limit 3 --json number,author \
            --jq "[.[] | select(.number < $current_pr_num)][0].author.login")

          a2=$(gh pr list --repo ${{ github.repository }} \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc" \
            --json number,author \
            --jq "[.[] | select(.number < $current_pr_num)][0].author.login")

          a3=$(gh pr list --repo ${{ github.repository }} \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc")
          
          a4=$(gh pr list --repo ${{ github.repository }} \
            --search "created:<${{ github.event.pull_request.created_at }} sort:created-desc" \
            --json number,author)

          a5=$(gh pr list --repo ${{ github.repository }} \
            --search "sort:created-desc" \
            --limit 3)
            
          a6=$(gh pr list --repo ${{ github.repository }} --limit 3)
          a6=$(gh pr list --repo "${{ github.repository }}" --limit 3 --json number | jq '.[].number')

          echo "a1: $a1"
          echo "a2: $a2"
          echo "a3: $a3"
          echo "a4: $a4"
          echo "a5: $a5"
          echo "a6: $a6"
