name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_repo=${{ github.repository }}
          current_pr_num=${{ github.event.number }}

          # 최근 3개의 PR 중 현재 PR 작성자와 다른 작성자 찾기 ()
          previous_pr_author=$(gh pr list --repo $current_repo \
            --search "sort:created-desc" \
            --limit 3 --json number,author \
            --jq 'map(select(.number < $current_pr_num))[0].author.login')

          previous_pr_author2=$(gh pr list --repo $current_repo \
            --search "sort:created-desc" \
            --limit 3 --json number,author \
            --jq '.[0].author.login')
          
          previous_pr_num2=$(gh pr list --repo $current_repo \
            --search "sort:created-desc" \
            --limit 3 --json number,author \
            --jq '.[0].number')

          echo "previous_pr_author: $previous_pr_author"
          echo "previous_pr_author2: $previous_pr_author2"
          echo "previous_pr_num2: $previous_pr_num2"
