name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  assign-reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_repo=${{ github.repository }}
          current_pr_num=${{ github.event.number }}

          # 최근 5개의 PR 중 현재 PR 작성자와 다른 작성자 찾기
          previous_pr_author=$(gh pr list --repo $current_repo --search "sort:created-desc" --limit 5 --state all --json number,author \
            --jq '[.[] | select(.number != '$current_pr_num' and .author.login != "'$current_pr_author'")][0].author.login')

          if [ -n "$previous_pr_author" ]; then
            gh pr edit $current_pr_num --repo $current_repo --add-reviewer bbFactory
            echo "✅ Assigned $previous_pr_author as reviewer to PR #$current_pr_num"
          else
            echo "❌ No previous PR author found to assign as reviewer"
          fi
