name: Automation

on:
  pull_request_target:

jobs:
  label-lang:
    runs-on: ubuntu-latest
    continue-on-error: true

    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ github.token }}

  assign_reviewer:
    runs-on: ubuntu-latest
    steps:
      - name: Get previous PR author and assign as reviewer
        env:
          GITHUB_TOKEN: ${{ github.token }}
        run: |
          current_pr_number=$(gh pr view --json number -q .number)
          # 이전 PR의 작성자 가져오기 (열린 PR 우선, 없으면 닫힌 PR)
          previous_pr_author=$(gh pr list --limit 2 --json author --jq 'map(select(.number != '$current_pr_number'))[0].author.login')
 
          if [ -z "$previous_pr_author" ]; then
            # 열린 PR이 없는 경우 닫힌 PR 확인
            previous_pr_author=$(gh pr list --limit 1 --state closed --json author --jq '.[0].author.login')
          fi
 
          if [ -n "$previous_pr_author" ]; then
            gh pr edit $current_pr_number --add-reviewer $previous_pr_author
            echo "Assigned $previous_pr_author as reviewer to PR #$current_pr_number"
          else
            echo "No previous PR author found to assign as reviewer"
          fi
