name: 🔄 Integration

on:
  pull_request:

jobs:
  linelint:
    runs-on: ubuntu-latest
    steps:
      - name: Check files without newline at end
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          PR_NUMBER=${{ github.event.number }}
          
          echo "Files without newline at end:"
          
          files_without_newline=$(gh pr view $PR_NUMBER --json files --repo ${{ github.repository }} \
            | jq -r '.files[] | select(.patch != null and (.patch | endswith("\n") | not)) | .path')
          
          if [ -n "$files_without_newline" ]; then
            echo "$files_without_newline"
            echo "::warning::Found files without newline at end"
