name: 🔄 Integration

on:
  pull_request:

jobs:
  line-ending-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Find files missing end line break
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files_without_newline=""
          for file in $files; do
            if [ "$(tail -c 1 $file | wc -l)" -eq 0 ]; then
              files_without_newline+=("$file")
            fi
          done
          
          if [ -n "$files_without_newline" ]; then
            echo "files_without_newline: $files_without_newline"
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo -e "$files_without_newline" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          fi

      - name: Set Job Summary
        if: failure()
        run: |
          if [ -n '${{ steps.newline-check.outputs.files }}' ]; then
          echo "🛠️ 아래 파일들에 공백 줄을 추가해주세요:" >> $GITHUB_STEP_SUMMARY
          echo '${{ steps.newline-check.outputs.files }}' |
            jq -r '.[]' |
            sed 's/^/- /' >> $GITHUB_STEP_SUMMARY
          fi
