name: 🔄 Integration

on:
  pull_request:

jobs:
  linelint:
    runs-on: ubuntu-latest
    steps:
      - name: Check files without newline at end
        run: |
          files_without_newline=$(git diff --name-only ${{ github.event.pull_request.base.sha }} | while read file; do
            if [ -f "$file" ] && [ "$(tail -c1 "$file" | wc -l)" -eq 0 ]; then
              echo "$file"
            fi
          done)
          
          if [ -n "$files_without_newline" ]; then
            echo "Files without newline at end:"
            echo "$files_without_newline"
            echo "::warning::Found files without newline at end"