name: 🔄 Integration

on:
  pull_request:

jobs:
  line-ending-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for missing newlines
        id: newline-check
        run: |
          git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }} |
            find -type f -exec grep -q -m 1 '$' {} \; -print0 |
            xargs -0 -n 1 -t echo >> $GITHUB_STEP_SUMMARY
          
          if [ $? -ne 0 ]; then
            echo "️ 아래 파일들에 공백 줄을 추가해주세요:" >> $GITHUB_STEP_SUMMARY
            exit 1
          fi