name: 🔄 Integration

on:
  pull_request:

jobs:
  line-ending-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find files missing end line break
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          success=true
          for file in $files; do
            if [ "$(tail -c 1 $file | wc -l)" -eq 0 ]; then
              echo "> $file" >> $GITHUB_STEP_SUMMARY
              success=false
            fi
          done
          
          if [ "$success" = false ]; then
            echo ":warning: 위 파일들의 마지막에 줄 바꿈(line break)을 추가해주세요." >> $GITHUB_STEP_SUMMARY
            exit 1
          fi