name: 🔄 Integration

on:
  pull_request:

jobs:
  line-ending-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Find files missing end line break
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.sha }})
          files_without_newline=""
          for file in $files; do
            if [ "$(tail -c 1 $file | wc -l)" -eq 0 ]; then
              echo "$file" >> $GITHUB_STEP_SUMMARY
              files_without_newline+=("$file")
            fi
          done
          echo "🛠️ 아래 파일들에 공백 줄을 추가해주세요:" >> $GITHUB_STEP_SUMMARY
